export const APP_CONFIG = Object.freeze({
  schemaVersion: 1,
  appName: "Baby Shower Valentino Gael",
  environment: "development",
  defaultRoute: "#/inicio",
  validRoutes: Object.freeze([
    "#/inicio",
    "#/detalles",
    "#/piscina",
    "#/confirmacion",
    "#/confirmacion/enviando",
    "#/confirmacion/exito",
    "#/confirmacion/error",
  ]),
  featureFlags: Object.freeze({
    routingEnabled: true,
    eventHydrationEnabled: true,
    rsvpUiEnabled: true,
    rsvpValidationEnabled: true,
    rsvpPersistenceEnabled: false,
    giftSelectionUiEnabled: true,
    mobileSectionSnapEnabled: true,
    agendaUiEnabled: false,
    photoAlbumUiEnabled: false,
    analyticsEnabled: false,
    deploymentEnabled: false,
    debugEnabled: false,
  }),
  selectors: Object.freeze({
    eventText: "[data-event-text]",
    routeLink: "a[href^='#/']",
    routeSection: "[data-route-section]",
    rsvpForm: "[data-rsvp-form]",
    rsvpStatus: "[data-rsvp-status]",
    rsvpSubmit: "[data-rsvp-submit]",
    rsvpField: "[data-rsvp-field]",
    giftOptions: "[data-gift-options]",
    otherGiftField: "[data-other-gift-field]",
    otherGiftInput: "[data-other-gift-input]",
  }),
  limits: Object.freeze({
    maxScrollFocusDelayMs: 120,
    minTouchTargetPx: 44,
  }),
  manifestPath: "docs/FILE_MANIFEST.sha256",
});
